spring:
  datasource:
    master:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASS}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        pool-name: MasterPool
        read-only: false
    replica:
      jdbc-url: jdbc:postgresql://${READ_REPLICA_DB_HOST}:${READ_REPLICA_DB_PORT}/${READ_REPLICA_DB_NAME}
      username: ${READ_REPLICA_DB_USER}
      password: ${READ_REPLICA_DB_PASS}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 30
        minimum-idle: 5
        pool-name: ReplicaPool
        read-only: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s        # how often to check for changes (default 1s)
      quiet-period: 1s         # wait after change before restarting (default 400ms)
      exclude: static/**,public/**,META-INF/maven/**
    livereload:
      enabled: false  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_URI}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        compression.type: snappy
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 500
      properties:
        spring.json.trusted.packages: "com.enterprise.product.*"
    listener:
      ack-mode: manual_immediate

aws:
  region: ${AWS_REGION:ap-south-1}
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    endpoint: ${S3_BUCKET_END_POINT_URI:none}
    path-style-access: true

logging:
  level:
    root: INFO
    com.enterprise.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
